env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
    cpu: 4
    memory: 8G
  matrix:
    compute_engine_instance:
      image: family/freebsd-15-0-snap
  info_script:
    - "uname -a"
