env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
    cpu: 4
    memory: 8G
  matrix:
    compute_engine_instance:
      image: family/freebsd-14-0
    compute_engine_instance:
      image: family/freebsd-15-0-snap
  prepare_script:
    - pkg install -y autoconf automake libtool gmake php83 php83-tokenizer
  configure_script:
    - env MAKE=gmake phpize
    - env MAKE=gmake ./configure
  build_script:
    - gmake -j `sysctl -n kern.smp.cpus`
  test_script:
    - gmake test 
